jobs:
  - name: spaceBar1
    type: runSh
    steps:
      - IN: sample-script
      #- IN: triggertest1
      - OUT: runImage
      - TASK:
        - script: sudo apt-get install tree
        - pwd
        - script: tree -F IN
        - script: IN/sample-script/gitRepo/echo.sh

  - name: spaceBar2
    type: runSh
    steps:
      - IN: runImage
      - IN: spaceBar1
      - TASK:
        - script: sudo apt-get install tree
        - pwd
        - script: tree -F IN
        - script: IN/sample-script-dup/gitRepo/echo.sh
        
